"""
Script generated by Claude on 2024-06-19 prompt: 
app.py file & how could I populate the karma scores for users that have interacted in the system before my update?
Edited to fix the app.py code to match the new karma rules, and to add a backfill_karma.py 
script that can be run to recompute karma for all users based on existing posts, comments, and reactions.

One-off script: rebuild karma_events and users.karma from existing data,
using the rules currently in app.py:

  - reaction on someone else's post -> 0.1 to the post owner, once per reactor per post
  - comment on someone else's post  -> 0.1 / 0.5 / 0.7 / 0.3 / 0.1 / 0 by post age
                                       (<1h, <12h, <24h, <72h, <120h, older)
      * different comments from the same commenter (even on the same post) each earn karma
      * identical normalized text earns karma only once per commenter (across all posts)
  - a post only earns karma if it is the author's FIRST post with that normalized text;
    later copies of the same text never earn (neither reactions nor comments)
  - the post owner's account must be at least 24h old when the event happened

It WIPES karma_events, creates the unique indexes, and recomputes everything,
so it is safe to re-run. Run it BEFORE starting the app, from the project folder:
    python backfill_karma.py
"""
import hashlib
import re
import shutil
import sqlite3
import sys
from datetime import datetime

DATABASE = sys.argv[1] if len(sys.argv) > 1 else "database.sqlite"


def normalize_text(text):
    """Must match normalize_text() in app.py."""
    text = re.sub(r"[^\w\s]", "", (text or "").lower())
    return re.sub(r"\s+", " ", text).strip()


def comment_hash(text):
    """Must match comment_hash() in app.py."""
    return hashlib.sha256(normalize_text(text).encode("utf-8")).hexdigest()


def comment_points(hours):
    """Must match the brackets in add_comment() in app.py."""
    if hours < 1:
        return 0.1
    if hours < 12:
        return 0.5
    if hours < 24:
        return 0.7
    if hours < 72:
        return 0.3
    if hours < 120:
        return 0.1
    return 0


REACTIONS_SQL = """
INSERT OR IGNORE INTO karma_events (user_id, event_type, source_id, points, actor_id)
SELECT p.user_id, 'reaction', r.post_id, 0.1, r.user_id
FROM reactions r
JOIN posts p ON p.id = r.post_id
JOIN users o ON o.id = p.user_id
WHERE p.user_id != r.user_id
  AND p.id NOT IN (SELECT id FROM dup_posts)
  AND (julianday('now') - julianday(o.created_at)) * 24.0 >= 24
"""  # reactions has no known timestamp, so account age is checked against "now"

COMMENTS_SQL = """
SELECT c.user_id AS actor_id, c.post_id, c.content, c.created_at, p.user_id AS owner_id,
       (julianday(c.created_at) - julianday(p.created_at)) * 24.0 AS hours
FROM comments c
JOIN posts p ON p.id = c.post_id
JOIN users o ON o.id = p.user_id
WHERE p.user_id != c.user_id
  AND p.id NOT IN (SELECT id FROM dup_posts)
  AND (julianday(c.created_at) - julianday(o.created_at)) * 24.0 >= 24
ORDER BY c.created_at, c.id
"""

TOTALS_SQL = """
UPDATE users
SET karma = COALESCE((SELECT SUM(points) FROM karma_events WHERE user_id = users.id), 0)
"""

EXPECTED_INDEXES = {
    "idx_karma_reaction_once",
    "idx_karma_comment_unique_text",
}

backup = f"{DATABASE}.bak-{datetime.now():%Y%m%d-%H%M%S}"
shutil.copy2(DATABASE, backup)
print(f"Backup written to {backup}")

conn = sqlite3.connect(DATABASE)
try:
    cur = conn.cursor()
    cur.execute("DELETE FROM karma_events")  # wipe first so the unique indexes can be created

    for col in ("actor_id INTEGER", "content_hash TEXT"):
        try:
            cur.execute(f"ALTER TABLE karma_events ADD COLUMN {col}")
        except sqlite3.OperationalError as e:
            if "duplicate column name" not in str(e):
                raise
    cur.execute("""CREATE UNIQUE INDEX IF NOT EXISTS idx_karma_reaction_once
                   ON karma_events (user_id, source_id, actor_id) WHERE event_type = 'reaction'""")
    cur.execute("DROP INDEX IF EXISTS idx_karma_comment_once_per_post")  # rule removed
    cur.execute("""CREATE UNIQUE INDEX IF NOT EXISTS idx_karma_comment_unique_text
                   ON karma_events (actor_id, content_hash) WHERE event_type = 'comment'""")

    # posts whose author already has an earlier post with the same normalized text
    seen, dup_ids = set(), []
    for post_id, author_id, content in cur.execute(
            "SELECT id, user_id, content FROM posts ORDER BY id").fetchall():
        key = (author_id, normalize_text(content))
        if key in seen:
            dup_ids.append(post_id)
        else:
            seen.add(key)
    cur.execute("CREATE TEMP TABLE dup_posts (id INTEGER PRIMARY KEY)")
    cur.executemany("INSERT INTO dup_posts VALUES (?)", [(i,) for i in dup_ids])
    print(f"Duplicate posts excluded from karma: {len(dup_ids)}")

    cur.execute(REACTIONS_SQL)
    reactions = cur.rowcount

    comments = 0
    for actor_id, post_id, content, created_at, owner_id, hours in cur.execute(COMMENTS_SQL).fetchall():
        points = comment_points(hours)
        if points <= 0 or not content or not content.strip():
            continue
        res = cur.execute(
            """INSERT OR IGNORE INTO karma_events
               (user_id, event_type, source_id, points, actor_id, content_hash, created_at)
               VALUES (?, 'comment', ?, ?, ?, ?, ?)""",
            (owner_id, post_id, points, actor_id, comment_hash(content), created_at),
        )
        comments += res.rowcount  # 0 when a unique index rejected it

    cur.execute(TOTALS_SQL)
    conn.commit()
except Exception:
    conn.rollback()
    raise

print(f"Inserted {reactions} reaction events and {comments} comment events.")
present = {r[0] for r in conn.execute(
    "SELECT name FROM sqlite_master WHERE type = 'index' AND name LIKE 'idx_karma%'")}
print("Karma indexes present:", ", ".join(sorted(present)) or "NONE")
if present != EXPECTED_INDEXES:
    print("WARNING: missing indexes:", ", ".join(sorted(EXPECTED_INDEXES - present)))
print("Top 10:")
for username, karma in conn.execute(
    "SELECT username, karma FROM users ORDER BY karma DESC, username LIMIT 10"
):
    print(f"  {username:<20} {karma:.1f}")
conn.close()