"""
Script generated by Claude on 2024-06-19 prompt: 
app.py file & how could I populate the karma scores for users that have interacted in the system before my update?

One-off script: rebuild karma_events and users.karma from existing data.

Mirrors the live rules in app.py:
  - reaction on someone else's post  -> 0.1 to the post owner (once per reactor per post)
  - comment on someone else's post   -> 0.1 / 0.5 / 0.7 / 0.3 / 0.1 / 0 depending on
                                        post age (<1h, <12h, <24h, <72h, <120h, older)
  - the post owner's account must be at least 24h old when the event happened

It WIPES karma_events and recomputes everything, so it is safe to re-run.
Run it from the project folder:  python backfill_karma.py
"""
import shutil
import sqlite3
import sys
from datetime import datetime

DATABASE = sys.argv[1] if len(sys.argv) > 1 else "database.sqlite"

# reactions has no known timestamp, so the 24h account-age rule uses "now"
REACTIONS_SQL = """
INSERT OR IGNORE INTO karma_events (user_id, event_type, source_id, points, actor_id)
SELECT p.user_id, 'reaction', r.post_id, 0.1, r.user_id
FROM reactions r
JOIN posts p ON p.id = r.post_id
JOIN users o ON o.id = p.user_id
WHERE p.user_id != r.user_id
  AND (julianday('now') - julianday(o.created_at)) * 24.0 >= 24
"""

COMMENTS_SQL = """
INSERT INTO karma_events (user_id, event_type, source_id, points, actor_id, created_at)
SELECT owner_id, 'comment', post_id,
       CASE WHEN h < 1   THEN 0.1
            WHEN h < 12  THEN 0.5
            WHEN h < 24  THEN 0.7
            WHEN h < 72  THEN 0.3
            ELSE 0.1 END,
       actor_id, created_at
FROM (
    SELECT p.user_id AS owner_id, c.post_id AS post_id, c.user_id AS actor_id,
           c.created_at AS created_at,
           (julianday(c.created_at) - julianday(p.created_at)) * 24.0 AS h
    FROM comments c
    JOIN posts p ON p.id = c.post_id
    JOIN users o ON o.id = p.user_id
    WHERE p.user_id != c.user_id
      AND (julianday(c.created_at) - julianday(o.created_at)) * 24.0 >= 24
      AND (julianday(c.created_at) - julianday(p.created_at)) * 24.0 < 120
)
"""

TOTALS_SQL = """
UPDATE users
SET karma = COALESCE((SELECT SUM(points) FROM karma_events WHERE user_id = users.id), 0)
"""

backup = f"{DATABASE}.bak-{datetime.now():%Y%m%d-%H%M%S}"
shutil.copy2(DATABASE, backup)
print(f"Backup written to {backup}")

conn = sqlite3.connect(DATABASE)
try:
    cur = conn.cursor()
    cur.execute("DELETE FROM karma_events")
    cur.execute(REACTIONS_SQL)
    reactions = cur.rowcount
    cur.execute(COMMENTS_SQL)
    comments = cur.rowcount
    cur.execute(TOTALS_SQL)
    conn.commit()
except Exception:
    conn.rollback()
    raise

print(f"Inserted {reactions} reaction events and {comments} comment events.")
print("Top 10:")
for username, karma in conn.execute(
    "SELECT username, karma FROM users ORDER BY karma DESC, username LIMIT 10"
):
    print(f"  {username:<20} {karma:.1f}")
conn.close()
